# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: Down to Earth discoveries
url:   http://kevinbett.com
author:
  name:    Kevin Bett        # For copyright notice and ATOM feeds
  email:   kevin.bett@gmail.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - http://depassion.myopenid.com
